// import "./globals.css";
import { TodoProvider } from "./context/TodoContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className = 'mt-10'>
        <TodoProvider>
          {children}
        </TodoProvider>
      </body>
    </html>
  );
}
